# Website details
name: Nick Scialli
description: JavaScript Developer
linkedin: "https://www.linkedin.com/in/nicholasscialli/"
author: Nick Scialli
lang: en
locale: en_US

# Jekyll
paginate: 10
highlighter: rouge
markdown: kramdown
plugins: [jekyll-paginate]
timezone: America/New_York
paginateLabel: page
paginate_path: "page/:num"
permalink: /:categories/:year/:month/:day/:title
baseurl: https://nick.scialli.me

# Includes
addthisId: ""
disqusUsername: ""
googleAnalyticsId: ""

# Search engine verifications
bing: ""
yandex: ""
google: ""

# Sitemap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/404.html"
  include_posts:
    - "/index.html"
  change_frequency_name: "daily"
  priority_name: "1.00"
